"""add bookings users relation

Revision ID: 01a5c615306a
Revises: 0cb957f20a43
Create Date: 2024-08-14 20:29:27.895976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a5c615306a'
down_revision: Union[str, None] = '0cb957f20a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'user_id')
    # ### end Alembic commands ###
