repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        name: app ruff
        args: [--exit-non-zero-on-fix]
        files: ^app/

      - id: ruff-format
        name: app ruff check format
        args: [--check]
        files: ^app/
