[tool.ruff]
line-length = 100
target-version = "py39"
exclude = ["app/migrations", "venv", ".git", "__pycache__"]
select = ["E", "F", "I", "B", "A"]
ignore = ["B008"]


[tool.pyright]
include = ["app"]