version: '3.5'

services:
  booking_pg:
    image: postgres
    volumes:
       - postgres:/data/postgres
       - ./postgres/init:/docker-entrypoint-initdb.d
    ports: # for local dev
      - "54321:5432" 
    networks:
      - postgres_nw
    restart: unless-stopped
    env_file:
      - ./.env

  booking_redis:
    image: redis:latest
    ports: # for local dev
      - "63792:6379"
    networks:
      - redis_nw

  booking_back:
    build:
      context: ../
    volumes:
      - booking_static_vol:/booking/app/static/
    ports: # for local dev
      - "888:8000"
    depends_on:
      - booking_pg
      - booking_redis
    networks:
      - postgres_nw
      - redis_nw
      - nginx_nw
    restart: always
    env_file:
      - ./.env
    command: /scripts/start_fastapi.sh

  booking_celery:
    build:
      context: ../
    volumes:
      - booking_static_vol:/booking/app/static/
    depends_on:
      - booking_pg
      - booking_redis
    networks:
      - postgres_nw
      - redis_nw
    restart: always
    env_file:
      - ./.env
    command: ["/scripts/start_celery.sh", "celery"]

  booking_flower:
    build:
      context: ../
    volumes:
      - booking_static_vol:/booking/app/static/
    depends_on:
      - booking_celery
    networks:
      - postgres_nw
      - redis_nw
      - nginx_nw
    env_file:
      - ./.env
    command: ["/scripts/start_celery.sh", "flower"]

  booking_nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - booking_back
      - booking_flower
    networks:
      - nginx_nw
    restart: unless-stopped


networks:
  postgres_nw:
    driver: bridge
  redis_nw:
    driver: bridge
  nginx_nw:
    driver: bridge

volumes:
    booking_static_vol:
    postgres:
    pgadmin: